### ISSUE TITLE
Unable to build the project in the MS Visual studio 2017.

### ISSUE THREAD

**Issue by vishnu106** [demonguru18/Angular7DotNetCore2.1BootStrap4#1]
Getting the below same output after waiting for a long time. 

Can I please know the solution for this below issue.

![image](https://user-images.githubusercontent.com/13914714/47864903-c463e180-de20-11e8-9825-8eed308232c3.png)

**Comment by demonguru18** [comment]
Hi vishnu,
It is restoring the Node_modules folder as it was ignored in git.
But shouldn't take time.
here, it works for me fine.
![image](https://user-images.githubusercontent.com/4347612/47866033-17637780-ddd4-11e8-9926-2da1900f7b0d.png)

**Comment by demonguru18** [comment]
Here are the Steps to Execute - doc File
https://docs.google.com/document/d/1eXsBLjDavetyE-TnD2fnpisCkHWfRHTUVOjRIrgnEEM/edit?usp=sharing

**Comment by demonguru18** [comment]
Also Can you check you have - Updated version on Angular installed Globally
**ng version**
![image](https://user-images.githubusercontent.com/4347612/47867186-2ef02f80-ddd7-11e8-9673-ad6f4c26c75e.png)
If you don't see this, to Update angular globally
npm uninstall -g angular-cli
npm cache clean or npm cache verify (if npm > 5)
npm install -g @angular/cli@latest

**Comment by vishnu106** [comment]
Thank you @demonguru18 it helped me a lot...:)
